// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalentTrack.Data;

#nullable disable

namespace TalentTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewInterviewers", b =>
                {
                    b.Property<int>("InterviewId")
                        .HasColumnType("integer")
                        .HasColumnName("interview_id");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("interviewer_id");

                    b.HasKey("InterviewId", "InterviewerId")
                        .HasName("pk_interview_interviewers");

                    b.HasIndex("InterviewerId")
                        .HasDatabaseName("ix_interview_interviewers_interviewer_id");

                    b.ToTable("interview_interviewers", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ResetOTP")
                        .HasColumnType("text")
                        .HasColumnName("reset_otp");

                    b.Property<DateTime?>("ResetOTPExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reset_otp_expiry");

                    b.Property<string>("Resume")
                        .HasColumnType("text")
                        .HasColumnName("resume");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.HasKey("CandidateId")
                        .HasName("pk_candidates");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("applied_date");

                    b.Property<string>("BackgroundVerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("background_verification_status");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ApplicationId")
                        .HasName("pk_candidate_applications");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_candidate_applications_job_id");

                    b.HasIndex("CandidateId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_applications_candidate_id_job_id");

                    b.ToTable("candidate_applications", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DocumentId")
                        .HasName("pk_candidate_documents");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_candidate_documents_candidate_id");

                    b.ToTable("candidate_documents", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("candidate_skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateSkillId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.HasKey("CandidateSkillId")
                        .HasName("pk_candidate_skills");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_candidate_skills_candidate_id");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.FeedbackSkillRating", b =>
                {
                    b.Property<int>("FeedbackSkillRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("feedback_skill_rating_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackSkillRatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_id");

                    b.Property<int?>("JobSkillId")
                        .HasColumnType("integer")
                        .HasColumnName("job_skill_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FeedbackSkillRatingId")
                        .HasName("pk_feedback_skill_ratings");

                    b.HasIndex("FeedbackId")
                        .HasDatabaseName("ix_feedback_skill_ratings_feedback_id");

                    b.HasIndex("JobSkillId")
                        .HasDatabaseName("ix_feedback_skill_ratings_job_skill_id");

                    b.ToTable("feedback_skill_ratings", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interview_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("interview_date");

                    b.Property<int?>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InterviewId")
                        .HasName("pk_interviews");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_interviews_candidate_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_interviews_job_id");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.InterviewFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("feedback_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("integer")
                        .HasColumnName("communication_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InterviewId")
                        .HasColumnType("integer")
                        .HasColumnName("interview_id");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("interviewer_id");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("ProblemSolvingScore")
                        .HasColumnType("integer")
                        .HasColumnName("problem_solving_score");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<string>("Strengths")
                        .HasColumnType("text")
                        .HasColumnName("strengths");

                    b.Property<int>("TechnicalScore")
                        .HasColumnType("integer")
                        .HasColumnName("technical_score");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("text")
                        .HasColumnName("weaknesses");

                    b.HasKey("FeedbackId")
                        .HasName("pk_interview_feedbacks");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_interview_feedbacks_candidate_id");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("ix_interview_feedbacks_interview_id");

                    b.HasIndex("InterviewerId")
                        .HasDatabaseName("ix_interview_feedbacks_interviewer_id");

                    b.ToTable("interview_feedbacks", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.InterviewParticipant", b =>
                {
                    b.Property<int>("InterviewParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interview_participant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterviewParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InterviewId")
                        .HasColumnType("integer")
                        .HasColumnName("interview_id");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("integer")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InterviewParticipantId")
                        .HasName("pk_interview_participants");

                    b.HasIndex("RecruiterId")
                        .HasDatabaseName("ix_interview_participants_recruiter_id");

                    b.HasIndex("InterviewId", "RecruiterId")
                        .IsUnique()
                        .HasDatabaseName("ix_interview_participants_interview_id_recruiter_id");

                    b.ToTable("interview_participants", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.Interviewer", b =>
                {
                    b.Property<int>("InterviewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interviewer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterviewerId"));

                    b.Property<string>("AvatarInitials")
                        .HasColumnType("text")
                        .HasColumnName("avatar_initials");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text")
                        .HasColumnName("linked_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Specialization")
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("InterviewerId")
                        .HasName("pk_interviewers");

                    b.ToTable("interviewers", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewerId = 1,
                            AvatarInitials = "PS",
                            Bio = "Senior Software Engineer with 8+ years of experience.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "interviewer@talenttrack.com",
                            LinkedIn = "linkedin.com/in/priyasharma",
                            Name = "Priya Sharma",
                            Password = "interviewer123",
                            Phone = "+91 98765 43210",
                            Specialization = "Full Stack Development",
                            YearsExperience = 8
                        });
                });

            modelBuilder.Entity("TalentTrack.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("JobId")
                        .HasName("pk_jobs");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.JobSkill", b =>
                {
                    b.Property<int>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobSkillId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer")
                        .HasColumnName("required_experience");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("JobSkillId")
                        .HasName("pk_job_skills");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_skills_job_id");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_role");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<string>("TargetUserEmail")
                        .HasColumnType("text")
                        .HasColumnName("target_user_email");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.OfferLetter", b =>
                {
                    b.Property<int>("OfferLetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("offer_letter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferLetterId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joining_date");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("offer_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OfferLetterId")
                        .HasName("pk_offer_letters");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_offer_letters_application_id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_offer_letters_candidate_id");

                    b.ToTable("offer_letters", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recruiter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecruiterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ResetOTP")
                        .HasColumnType("text")
                        .HasColumnName("reset_otp");

                    b.Property<DateTime?>("ResetOTPExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reset_otp_expiry");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("RecruiterId")
                        .HasName("pk_recruiters");

                    b.ToTable("recruiters", (string)null);

                    b.HasData(
                        new
                        {
                            RecruiterId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Department = "Administration",
                            Email = "admin@talenttrack.com",
                            IsApproved = true,
                            Name = "System Admin",
                            Password = "admin123",
                            Phone = "+91 99999 88888",
                            Role = "Admin",
                            Status = "Approved"
                        },
                        new
                        {
                            RecruiterId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Department = "Human Resources",
                            Email = "recruiter@talenttrack.com",
                            IsApproved = true,
                            Name = "Mansi Verma",
                            Password = "recruiter123",
                            Phone = "+91 98765 11111",
                            Role = "Recruiter",
                            Status = "Approved"
                        },
                        new
                        {
                            RecruiterId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Department = "Engineering",
                            Email = "interviewer@talenttrack.com",
                            IsApproved = true,
                            Name = "Priya Sharma",
                            Password = "interviewer123",
                            Phone = "+91 98765 43210",
                            Role = "Interviewer",
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("TalentTrack.Models.Screening", b =>
                {
                    b.Property<int>("ScreeningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScreeningId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ScreenedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("screened_by_user_id");

                    b.Property<DateTime>("ScreeningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("screening_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ScreeningId")
                        .HasName("pk_screenings");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_screenings_application_id");

                    b.ToTable("screenings", (string)null);
                });

            modelBuilder.Entity("TalentTrack.Models.ScreeningSkillEvaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaluationId"));

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<bool>("HasSkill")
                        .HasColumnType("boolean")
                        .HasColumnName("has_skill");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.HasKey("EvaluationId")
                        .HasName("pk_screening_skill_evaluations");

                    b.HasIndex("ScreeningId")
                        .HasDatabaseName("ix_screening_skill_evaluations_screening_id");

                    b.ToTable("screening_skill_evaluations", (string)null);
                });

            modelBuilder.Entity("InterviewInterviewers", b =>
                {
                    b.HasOne("TalentTrack.Models.Interview", null)
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_interviewers_interviews_interview_id");

                    b.HasOne("TalentTrack.Models.Interviewer", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_interviewers_interviewers_interviewer_id");
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateApplication", b =>
                {
                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_applications_candidates_candidate_id");

                    b.HasOne("TalentTrack.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_applications_jobs_job_id");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateDocument", b =>
                {
                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_documents_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("TalentTrack.Models.CandidateSkill", b =>
                {
                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_skills_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("TalentTrack.Models.FeedbackSkillRating", b =>
                {
                    b.HasOne("TalentTrack.Models.InterviewFeedback", "Feedback")
                        .WithMany("SkillRatings")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_skill_ratings_interview_feedbacks_feedback_id");

                    b.HasOne("TalentTrack.Models.JobSkill", "JobSkill")
                        .WithMany()
                        .HasForeignKey("JobSkillId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_feedback_skill_ratings_job_skills_job_skill_id");

                    b.Navigation("Feedback");

                    b.Navigation("JobSkill");
                });

            modelBuilder.Entity("TalentTrack.Models.Interview", b =>
                {
                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interviews_candidates_candidate_id");

                    b.HasOne("TalentTrack.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_interviews_jobs_job_id");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentTrack.Models.InterviewFeedback", b =>
                {
                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interview_feedbacks_candidates_candidate_id");

                    b.HasOne("TalentTrack.Models.Interview", "Interview")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_feedbacks_interviews_interview_id");

                    b.HasOne("TalentTrack.Models.Interviewer", "Interviewer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interview_feedbacks_interviewers_interviewer_id");

                    b.Navigation("Candidate");

                    b.Navigation("Interview");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("TalentTrack.Models.InterviewParticipant", b =>
                {
                    b.HasOne("TalentTrack.Models.Interview", "Interview")
                        .WithMany("Participants")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_participants_interviews_interview_id");

                    b.HasOne("TalentTrack.Models.Recruiter", "Recruiter")
                        .WithMany("InterviewParticipants")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interview_participants_recruiters_recruiter_id");

                    b.Navigation("Interview");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("TalentTrack.Models.JobSkill", b =>
                {
                    b.HasOne("TalentTrack.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_skills_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentTrack.Models.OfferLetter", b =>
                {
                    b.HasOne("TalentTrack.Models.CandidateApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_offer_letters_candidate_applications_application_id");

                    b.HasOne("TalentTrack.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offer_letters_candidates_candidate_id");

                    b.Navigation("Application");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("TalentTrack.Models.Screening", b =>
                {
                    b.HasOne("TalentTrack.Models.CandidateApplication", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_candidate_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentTrack.Models.ScreeningSkillEvaluation", b =>
                {
                    b.HasOne("TalentTrack.Models.Screening", "Screening")
                        .WithMany("SkillEvaluations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screening_skill_evaluations_screenings_screening_id");

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("TalentTrack.Models.Candidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("TalentTrack.Models.Interview", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TalentTrack.Models.InterviewFeedback", b =>
                {
                    b.Navigation("SkillRatings");
                });

            modelBuilder.Entity("TalentTrack.Models.Interviewer", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("TalentTrack.Models.Job", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("TalentTrack.Models.Recruiter", b =>
                {
                    b.Navigation("InterviewParticipants");
                });

            modelBuilder.Entity("TalentTrack.Models.Screening", b =>
                {
                    b.Navigation("SkillEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
